[package]
name = "openvr"
version = "0.4.0"
authors = [
    "Colin Sherratt",
    "Erick Tryzelaar",
    "Rene Eichhorn"
]
license-file = "LICENSE.md"

documentation = "http://rust-openvr.github.io/rust-openvr/openvr/index.html"
homepage = "https://github.com/rust-openvr/rust-openvr"
repository = "https://github.com/rust-openvr/rust-openvr"

description = "A safe binding for openvr."

[lib]
name = "openvr"
path = "src/lib.rs"

[dependencies]
openvr_sys = { git = "https://github.com/wehjin/rust-openvr-sys" }

[dev_dependencies]
glium = "0.14.0"
num = "0.1.31"
nalgebra = "0.8.2"
